/*
 Navicat Premium Data Transfer

 Source Server         : pgsql
 Source Server Type    : PostgreSQL
 Source Server Version : 130015
 Source Host           : localhost:5432
 Source Catalog        : teqin
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 130015
 File Encoding         : 65001

 Date: 21/02/2025 13:41:12
*/


-- ----------------------------
-- Table structure for t_dc_party_individual
-- ----------------------------
DROP TABLE IF EXISTS "public"."t_dc_party_individual";
CREATE TABLE "public"."t_dc_party_individual" (
  "party_id" varchar(255) COLLATE "pg_catalog"."default",
  "birthday" varchar(255) COLLATE "pg_catalog"."default",
  "marital_status" varchar(255) COLLATE "pg_catalog"."default",
  "gender" varchar(255) COLLATE "pg_catalog"."default",
  "nationality" varchar(255) COLLATE "pg_catalog"."default",
  "nation" varchar(255) COLLATE "pg_catalog"."default",
  "education_level" varchar(255) COLLATE "pg_catalog"."default",
  "employer" varchar(255) COLLATE "pg_catalog"."default",
  "employer_type" varchar(255) COLLATE "pg_catalog"."default",
  "religion" varchar(255) COLLATE "pg_catalog"."default",
  "blood_type" varchar(255) COLLATE "pg_catalog"."default",
  "jt_politics" varchar(255) COLLATE "pg_catalog"."default",
  "pic" varchar(255) COLLATE "pg_catalog"."default",
  "fingerprint" varchar(255) COLLATE "pg_catalog"."default",
  "i_residence" varchar(255) COLLATE "pg_catalog"."default",
  "resident_birthplace" varchar(255) COLLATE "pg_catalog"."default",
  "pic_url" varchar(255) COLLATE "pg_catalog"."default",
  "status" varchar(255) COLLATE "pg_catalog"."default",
  "status_time" varchar(255) COLLATE "pg_catalog"."default",
  "health_status" varchar(255) COLLATE "pg_catalog"."default",
  "die_date" varchar(255) COLLATE "pg_catalog"."default",
  "die_reason" varchar(255) COLLATE "pg_catalog"."default",
  "height" varchar(255) COLLATE "pg_catalog"."default",
  "used_name" varchar(255) COLLATE "pg_catalog"."default",
  "profession_type" varchar(255) COLLATE "pg_catalog"."default",
  "employer_addr" varchar(255) COLLATE "pg_catalog"."default",
  "employer_code" varchar(255) COLLATE "pg_catalog"."default",
  "father_name" varchar(255) COLLATE "pg_catalog"."default",
  "father_id" varchar(255) COLLATE "pg_catalog"."default",
  "mother_name" varchar(255) COLLATE "pg_catalog"."default",
  "mother_id" varchar(255) COLLATE "pg_catalog"."default",
  "residence_no" varchar(255) COLLATE "pg_catalog"."default",
  "residence_house_no" varchar(255) COLLATE "pg_catalog"."default",
  "cert_type" varchar(255) COLLATE "pg_catalog"."default",
  "party_name" varchar(255) COLLATE "pg_catalog"."default",
  "identity_card" varchar(255) COLLATE "pg_catalog"."default",
  "cid_start_date" varchar(255) COLLATE "pg_catalog"."default",
  "cid_end_date" varchar(255) COLLATE "pg_catalog"."default",
  "born_country" varchar(255) COLLATE "pg_catalog"."default",
  "description" varchar(255) COLLATE "pg_catalog"."default",
  "home_phone" varchar(255) COLLATE "pg_catalog"."default",
  "mobile_phone" varchar(255) COLLATE "pg_catalog"."default",
  "family_address" varchar(255) COLLATE "pg_catalog"."default",
  "change_times" varchar(255) COLLATE "pg_catalog"."default",
  "create_user" varchar(255) COLLATE "pg_catalog"."default",
  "create_time" varchar(255) COLLATE "pg_catalog"."default",
  "update_user" varchar(255) COLLATE "pg_catalog"."default",
  "cj_org_code" varchar(255) COLLATE "pg_catalog"."default",
  "data_status" varchar(255) COLLATE "pg_catalog"."default",
  "is_to_es" varchar(255) COLLATE "pg_catalog"."default",
  "en_first_name" varchar(255) COLLATE "pg_catalog"."default",
  "en_name" varchar(255) COLLATE "pg_catalog"."default",
  "army_status" varchar(255) COLLATE "pg_catalog"."default",
  "health_condition" varchar(255) COLLATE "pg_catalog"."default",
  "health_condition_detail" varchar(255) COLLATE "pg_catalog"."default",
  "employer_addr_phone" varchar(255) COLLATE "pg_catalog"."default",
  "qr_code" varchar(255) COLLATE "pg_catalog"."default",
  "address_data_source" varchar(255) COLLATE "pg_catalog"."default",
  "army" varchar(255) COLLATE "pg_catalog"."default",
  "province_id" varchar(255) COLLATE "pg_catalog"."default",
  "housepersonid" varchar(255) COLLATE "pg_catalog"."default",
  "is_to_province" varchar(255) COLLATE "pg_catalog"."default",
  "has_vehicle" varchar(255) COLLATE "pg_catalog"."default",
  "is_employment" varchar(255) COLLATE "pg_catalog"."default",
  "is_only_child" varchar(255) COLLATE "pg_catalog"."default",
  "is_overseas_chinese_family" varchar(255) COLLATE "pg_catalog"."default",
  "management_categories" varchar(255) COLLATE "pg_catalog"."default",
  "speciality_specialty" varchar(255) COLLATE "pg_catalog"."default",
  "is_focus" varchar(255) COLLATE "pg_catalog"."default",
  "is_empty_hang" varchar(255) COLLATE "pg_catalog"."default",
  "is_perfect" varchar(255) COLLATE "pg_catalog"."default",
  "we_chat" varchar(255) COLLATE "pg_catalog"."default",
  "out_to_work" varchar(255) COLLATE "pg_catalog"."default",
  "is_location" varchar(255) COLLATE "pg_catalog"."default",
  "inoculation_times" varchar(255) COLLATE "pg_catalog"."default",
  "inoculation_org" varchar(255) COLLATE "pg_catalog"."default",
  "inoculation_first" varchar(255) COLLATE "pg_catalog"."default",
  "inoculation_second" varchar(255) COLLATE "pg_catalog"."default",
  "nucleic_test" varchar(255) COLLATE "pg_catalog"."default",
  "nucleic_test_time" varchar(255) COLLATE "pg_catalog"."default",
  "inoculation_third" varchar(255) COLLATE "pg_catalog"."default",
  "work_status" varchar(255) COLLATE "pg_catalog"."default",
  "work_type" varchar(255) COLLATE "pg_catalog"."default",
  "no_work_reason" varchar(255) COLLATE "pg_catalog"."default",
  "work_wish" varchar(255) COLLATE "pg_catalog"."default",
  "skills_cert" varchar(255) COLLATE "pg_catalog"."default",
  "hj_status" varchar(255) COLLATE "pg_catalog"."default",
  "vehicle_type" varchar(255) COLLATE "pg_catalog"."default",
  "vehicle_no" varchar(255) COLLATE "pg_catalog"."default",
  "work_time" varchar(255) COLLATE "pg_catalog"."default",
  "vocation_qualify" varchar(255) COLLATE "pg_catalog"."default",
  "remark" varchar(255) COLLATE "pg_catalog"."default",
  "hj_systemid" varchar(255) COLLATE "pg_catalog"."default",
  "hj_org_id" varchar(255) COLLATE "pg_catalog"."default",
  "hj_org_name" varchar(255) COLLATE "pg_catalog"."default",
  "business_license" varchar(255) COLLATE "pg_catalog"."default",
  "as_shareholder_director" varchar(255) COLLATE "pg_catalog"."default",
  "school_in_rongdong" varchar(255) COLLATE "pg_catalog"."default",
  "school" varchar(255) COLLATE "pg_catalog"."default",
  "parent_pickup" varchar(255) COLLATE "pg_catalog"."default",
  "transportation_school" varchar(255) COLLATE "pg_catalog"."default",
  "bus_reservation" varchar(255) COLLATE "pg_catalog"."default",
  "special_skills" varchar(255) COLLATE "pg_catalog"."default",
  "honorary_title" varchar(255) COLLATE "pg_catalog"."default",
  "demand_demand" varchar(255) COLLATE "pg_catalog"."default",
  "sync_time" varchar(255) COLLATE "pg_catalog"."default",
  "bdp_audit" varchar(255) COLLATE "pg_catalog"."default",
  "unionkey" varchar(255) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "user_design_id" int4 NOT NULL,
  "building_id" varchar(255) COLLATE "pg_catalog"."default",
  "org_id" varchar(255) COLLATE "pg_catalog"."default",
  "re_sn" varchar(255) COLLATE "pg_catalog"."default",
  "building_name" varchar(255) COLLATE "pg_catalog"."default",
  "building_address" varchar(255) COLLATE "pg_catalog"."default",
  "building_number" varchar(255) COLLATE "pg_catalog"."default",
  "building_floor" varchar(255) COLLATE "pg_catalog"."default",
  "building_elevator" varchar(255) COLLATE "pg_catalog"."default",
  "household_number" varchar(255) COLLATE "pg_catalog"."default",
  "load_time" varchar(255) COLLATE "pg_catalog"."default",
  "update_date" varchar(255) COLLATE "pg_catalog"."default",
  "longitude" varchar(255) COLLATE "pg_catalog"."default",
  "latitude" varchar(255) COLLATE "pg_catalog"."default",
  "room_type" varchar(255) COLLATE "pg_catalog"."default",
  "custom_code" varchar(255) COLLATE "pg_catalog"."default",
  "building_type" varchar(255) COLLATE "pg_catalog"."default",
  "hight" varchar(255) COLLATE "pg_catalog"."default",
  "area" varchar(255) COLLATE "pg_catalog"."default",
  "building_year" varchar(255) COLLATE "pg_catalog"."default",
  "org_code" varchar(255) COLLATE "pg_catalog"."default",
  "use_nature" varchar(255) COLLATE "pg_catalog"."default",
  "owner" varchar(255) COLLATE "pg_catalog"."default",
  "ground_floor_num" varchar(255) COLLATE "pg_catalog"."default",
  "underground_floor_num" varchar(255) COLLATE "pg_catalog"."default",
  "management_company" varchar(255) COLLATE "pg_catalog"."default",
  "admin_phone" varchar(255) COLLATE "pg_catalog"."default",
  "developer" varchar(255) COLLATE "pg_catalog"."default",
  "building_exterior_figure" varchar(255) COLLATE "pg_catalog"."default",
  "floor_structure" varchar(255) COLLATE "pg_catalog"."default",
  "fire_fighting_describe" varchar(255) COLLATE "pg_catalog"."default",
  "building_status" varchar(255) COLLATE "pg_catalog"."default",
  "project_status" varchar(255) COLLATE "pg_catalog"."default",
  "grid_id" varchar(255) COLLATE "pg_catalog"."default",
  "create_date" varchar(255) COLLATE "pg_catalog"."default",
  "land_nature" varchar(255) COLLATE "pg_catalog"."default",
  "building_area" varchar(255) COLLATE "pg_catalog"."default",
  "business_pattern" varchar(255) COLLATE "pg_catalog"."default",
  "building_dominant_forms" varchar(255) COLLATE "pg_catalog"."default",
  "business_area" varchar(255) COLLATE "pg_catalog"."default",
  "business_floor" varchar(255) COLLATE "pg_catalog"."default",
  "memory_area" varchar(255) COLLATE "pg_catalog"."default",
  "average_rent" varchar(255) COLLATE "pg_catalog"."default",
  "property_price" varchar(255) COLLATE "pg_catalog"."default",
  "electricity_price" varchar(255) COLLATE "pg_catalog"."default",
  "water_price" varchar(255) COLLATE "pg_catalog"."default",
  "whether_economic_building" varchar(255) COLLATE "pg_catalog"."default",
  "ground_parking_space" varchar(255) COLLATE "pg_catalog"."default",
  "underground_parking_space" varchar(255) COLLATE "pg_catalog"."default",
  "newbuid" varchar(255) COLLATE "pg_catalog"."default",
  "grid_code" varchar(255) COLLATE "pg_catalog"."default",
  "building_nature" varchar(255) COLLATE "pg_catalog"."default",
  "land_cadastral_id" varchar(255) COLLATE "pg_catalog"."default",
  "building_structure" varchar(255) COLLATE "pg_catalog"."default",
  "owner_user_tel" varchar(255) COLLATE "pg_catalog"."default",
  "owner_user" varchar(255) COLLATE "pg_catalog"."default",
  "unit_number" varchar(255) COLLATE "pg_catalog"."default",
  "per_number" varchar(255) COLLATE "pg_catalog"."default",
  "manager_rs_id" varchar(255) COLLATE "pg_catalog"."default",
  "standard_address" varchar(255) COLLATE "pg_catalog"."default",
  "building_addr" varchar(255) COLLATE "pg_catalog"."default",
  "buidling_addr_housno" varchar(255) COLLATE "pg_catalog"."default",
  "building_tag" varchar(255) COLLATE "pg_catalog"."default",
  "manager_name" varchar(255) COLLATE "pg_catalog"."default",
  "manager_phone" varchar(255) COLLATE "pg_catalog"."default",
  "address_type" varchar(255) COLLATE "pg_catalog"."default",
  "is_refresh_manager" varchar(255) COLLATE "pg_catalog"."default",
  "buildsrc_type" varchar(255) COLLATE "pg_catalog"."default",
  "tudicardid" varchar(255) COLLATE "pg_catalog"."default",
  "fangcardid" varchar(255) COLLATE "pg_catalog"."default",
  "intro" varchar(255) COLLATE "pg_catalog"."default",
  "td_hs_new" varchar(255) COLLATE "pg_catalog"."default",
  "td_marker_new" varchar(255) COLLATE "pg_catalog"."default",
  "thd_hs_new" varchar(255) COLLATE "pg_catalog"."default",
  "thd_marker_new" varchar(255) COLLATE "pg_catalog"."default",
  "td_hs_old" varchar(255) COLLATE "pg_catalog"."default",
  "td_marker_old" varchar(255) COLLATE "pg_catalog"."default",
  "thd_hs_old" varchar(255) COLLATE "pg_catalog"."default",
  "thd_marker_old" varchar(255) COLLATE "pg_catalog"."default",
  "manager_idcard" varchar(255) COLLATE "pg_catalog"."default",
  "manager_education_level" varchar(255) COLLATE "pg_catalog"."default",
  "manager_birthday" varchar(255) COLLATE "pg_catalog"."default",
  "manager_politics" varchar(255) COLLATE "pg_catalog"."default",
  "manager_gender" varchar(255) COLLATE "pg_catalog"."default",
  "community_name" varchar(255) COLLATE "pg_catalog"."default",
  "guid" varchar(255) COLLATE "pg_catalog"."default",
  "address_id" varchar(255) COLLATE "pg_catalog"."default",
  "is_synchronization" varchar(255) COLLATE "pg_catalog"."default",
  "upfloor" varchar(255) COLLATE "pg_catalog"."default",
  "underfloor" varchar(255) COLLATE "pg_catalog"."default",
  "correction_status" varchar(255) COLLATE "pg_catalog"."default",
  "elem_type" varchar(255) COLLATE "pg_catalog"."default",
  "in_use" varchar(255) COLLATE "pg_catalog"."default",
  "is_exist" varchar(255) COLLATE "pg_catalog"."default",
  "is_unit_continuity" varchar(255) COLLATE "pg_catalog"."default",
  "building_room_type" varchar(255) COLLATE "pg_catalog"."default",
  "household_rs_number" varchar(255) COLLATE "pg_catalog"."default",
  "danger_type" varchar(255) COLLATE "pg_catalog"."default",
  "base_type" varchar(255) COLLATE "pg_catalog"."default",
  "design_situation" varchar(255) COLLATE "pg_catalog"."default",
  "is_sketch" varchar(255) COLLATE "pg_catalog"."default",
  "transformation" varchar(255) COLLATE "pg_catalog"."default",
  "is_entrust" varchar(255) COLLATE "pg_catalog"."default",
  "is_approval" varchar(255) COLLATE "pg_catalog"."default",
  "six_types" varchar(255) COLLATE "pg_catalog"."default",
  "building_handle_status" varchar(255) COLLATE "pg_catalog"."default",
  "check_status" varchar(255) COLLATE "pg_catalog"."default",
  "estate_id" varchar(255) COLLATE "pg_catalog"."default"
)
;
COMMENT ON TABLE "public"."t_dc_party_individual" IS '智慧社区_人员信息表';

-- ----------------------------
-- Indexes structure for table t_dc_party_individual
-- ----------------------------
CREATE INDEX "index_t_dc_part_individual_part_id_copy1" ON "public"."t_dc_party_individual" USING btree (
  "party_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "index_t_dc_party_individual_copy1" ON "public"."t_dc_party_individual" USING btree (
  "party_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "gender" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "nationality" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "employer" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "employer_type" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "i_residence" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "resident_birthplace" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "party_name" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "mobile_phone" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
