/*
 Navicat Premium Data Transfer

 Source Server         : pgsql
 Source Server Type    : PostgreSQL
 Source Server Version : 130015
 Source Host           : localhost:5432
 Source Catalog        : teqin
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 130015
 File Encoding         : 65001

 Date: 21/02/2025 13:40:06
*/


-- ----------------------------
-- Table structure for t_dc_area_building_info
-- ----------------------------
DROP TABLE IF EXISTS "public"."t_dc_area_building_info";
CREATE TABLE "public"."t_dc_area_building_info" (
  "building_id" varchar(255) COLLATE "pg_catalog"."default",
  "org_id" varchar(255) COLLATE "pg_catalog"."default",
  "re_sn" varchar(255) COLLATE "pg_catalog"."default",
  "building_name" varchar(255) COLLATE "pg_catalog"."default",
  "building_address" varchar(255) COLLATE "pg_catalog"."default",
  "building_number" varchar(255) COLLATE "pg_catalog"."default",
  "building_floor" varchar(255) COLLATE "pg_catalog"."default",
  "building_elevator" varchar(255) COLLATE "pg_catalog"."default",
  "household_number" varchar(255) COLLATE "pg_catalog"."default",
  "remark" varchar(255) COLLATE "pg_catalog"."default",
  "load_time" varchar(255) COLLATE "pg_catalog"."default",
  "update_date" varchar(255) COLLATE "pg_catalog"."default",
  "status" varchar(255) COLLATE "pg_catalog"."default",
  "status_time" varchar(255) COLLATE "pg_catalog"."default",
  "longitude" varchar(255) COLLATE "pg_catalog"."default",
  "latitude" varchar(255) COLLATE "pg_catalog"."default",
  "room_type" varchar(255) COLLATE "pg_catalog"."default",
  "custom_code" varchar(255) COLLATE "pg_catalog"."default",
  "building_type" varchar(255) COLLATE "pg_catalog"."default",
  "hight" varchar(255) COLLATE "pg_catalog"."default",
  "area" varchar(255) COLLATE "pg_catalog"."default",
  "building_year" varchar(255) COLLATE "pg_catalog"."default",
  "org_code" varchar(255) COLLATE "pg_catalog"."default",
  "use_nature" varchar(255) COLLATE "pg_catalog"."default",
  "owner" varchar(255) COLLATE "pg_catalog"."default",
  "ground_floor_num" varchar(255) COLLATE "pg_catalog"."default",
  "underground_floor_num" varchar(255) COLLATE "pg_catalog"."default",
  "management_company" varchar(255) COLLATE "pg_catalog"."default",
  "admin_phone" varchar(255) COLLATE "pg_catalog"."default",
  "developer" varchar(255) COLLATE "pg_catalog"."default",
  "building_exterior_figure" varchar(255) COLLATE "pg_catalog"."default",
  "floor_structure" varchar(255) COLLATE "pg_catalog"."default",
  "fire_fighting_describe" varchar(255) COLLATE "pg_catalog"."default",
  "building_status" varchar(255) COLLATE "pg_catalog"."default",
  "project_status" varchar(255) COLLATE "pg_catalog"."default",
  "grid_id" varchar(255) COLLATE "pg_catalog"."default",
  "create_user" varchar(255) COLLATE "pg_catalog"."default",
  "create_date" varchar(255) COLLATE "pg_catalog"."default",
  "update_user" varchar(255) COLLATE "pg_catalog"."default",
  "land_nature" varchar(255) COLLATE "pg_catalog"."default",
  "building_area" varchar(255) COLLATE "pg_catalog"."default",
  "business_pattern" varchar(255) COLLATE "pg_catalog"."default",
  "building_dominant_forms" varchar(255) COLLATE "pg_catalog"."default",
  "business_area" varchar(255) COLLATE "pg_catalog"."default",
  "business_floor" varchar(255) COLLATE "pg_catalog"."default",
  "memory_area" varchar(255) COLLATE "pg_catalog"."default",
  "average_rent" varchar(255) COLLATE "pg_catalog"."default",
  "property_price" varchar(255) COLLATE "pg_catalog"."default",
  "electricity_price" varchar(255) COLLATE "pg_catalog"."default",
  "water_price" varchar(255) COLLATE "pg_catalog"."default",
  "whether_economic_building" varchar(255) COLLATE "pg_catalog"."default",
  "ground_parking_space" varchar(255) COLLATE "pg_catalog"."default",
  "underground_parking_space" varchar(255) COLLATE "pg_catalog"."default",
  "newbuid" varchar(255) COLLATE "pg_catalog"."default",
  "grid_code" varchar(255) COLLATE "pg_catalog"."default",
  "building_nature" varchar(255) COLLATE "pg_catalog"."default",
  "land_cadastral_id" varchar(255) COLLATE "pg_catalog"."default",
  "building_structure" varchar(255) COLLATE "pg_catalog"."default",
  "owner_user_tel" varchar(255) COLLATE "pg_catalog"."default",
  "owner_user" varchar(255) COLLATE "pg_catalog"."default",
  "unit_number" varchar(255) COLLATE "pg_catalog"."default",
  "per_number" varchar(255) COLLATE "pg_catalog"."default",
  "manager_rs_id" varchar(255) COLLATE "pg_catalog"."default",
  "standard_address" varchar(255) COLLATE "pg_catalog"."default",
  "building_addr" varchar(255) COLLATE "pg_catalog"."default",
  "buidling_addr_housno" varchar(255) COLLATE "pg_catalog"."default",
  "building_tag" varchar(255) COLLATE "pg_catalog"."default",
  "manager_name" varchar(255) COLLATE "pg_catalog"."default",
  "manager_phone" varchar(255) COLLATE "pg_catalog"."default",
  "address_type" varchar(255) COLLATE "pg_catalog"."default",
  "is_refresh_manager" varchar(255) COLLATE "pg_catalog"."default",
  "buildsrc_type" varchar(255) COLLATE "pg_catalog"."default",
  "tudicardid" varchar(255) COLLATE "pg_catalog"."default",
  "fangcardid" varchar(255) COLLATE "pg_catalog"."default",
  "intro" varchar(255) COLLATE "pg_catalog"."default",
  "td_hs_new" varchar(255) COLLATE "pg_catalog"."default",
  "td_marker_new" varchar(255) COLLATE "pg_catalog"."default",
  "thd_hs_new" varchar(255) COLLATE "pg_catalog"."default",
  "thd_marker_new" varchar(255) COLLATE "pg_catalog"."default",
  "td_hs_old" varchar(255) COLLATE "pg_catalog"."default",
  "td_marker_old" varchar(255) COLLATE "pg_catalog"."default",
  "thd_hs_old" varchar(255) COLLATE "pg_catalog"."default",
  "thd_marker_old" varchar(255) COLLATE "pg_catalog"."default",
  "manager_idcard" varchar(255) COLLATE "pg_catalog"."default",
  "manager_education_level" varchar(255) COLLATE "pg_catalog"."default",
  "manager_birthday" varchar(255) COLLATE "pg_catalog"."default",
  "manager_politics" varchar(255) COLLATE "pg_catalog"."default",
  "manager_gender" varchar(255) COLLATE "pg_catalog"."default",
  "community_name" varchar(255) COLLATE "pg_catalog"."default",
  "is_to_es" varchar(255) COLLATE "pg_catalog"."default",
  "guid" varchar(255) COLLATE "pg_catalog"."default",
  "province_id" varchar(255) COLLATE "pg_catalog"."default",
  "address_id" varchar(255) COLLATE "pg_catalog"."default",
  "is_synchronization" varchar(255) COLLATE "pg_catalog"."default",
  "upfloor" varchar(255) COLLATE "pg_catalog"."default",
  "underfloor" varchar(255) COLLATE "pg_catalog"."default",
  "correction_status" varchar(255) COLLATE "pg_catalog"."default",
  "elem_type" varchar(255) COLLATE "pg_catalog"."default",
  "in_use" varchar(255) COLLATE "pg_catalog"."default",
  "is_exist" varchar(255) COLLATE "pg_catalog"."default",
  "is_unit_continuity" varchar(255) COLLATE "pg_catalog"."default",
  "building_room_type" varchar(255) COLLATE "pg_catalog"."default",
  "household_rs_number" varchar(255) COLLATE "pg_catalog"."default",
  "is_perfect" varchar(255) COLLATE "pg_catalog"."default",
  "danger_type" varchar(255) COLLATE "pg_catalog"."default",
  "base_type" varchar(255) COLLATE "pg_catalog"."default",
  "design_situation" varchar(255) COLLATE "pg_catalog"."default",
  "is_sketch" varchar(255) COLLATE "pg_catalog"."default",
  "transformation" varchar(255) COLLATE "pg_catalog"."default",
  "is_entrust" varchar(255) COLLATE "pg_catalog"."default",
  "is_approval" varchar(255) COLLATE "pg_catalog"."default",
  "six_types" varchar(255) COLLATE "pg_catalog"."default",
  "building_handle_status" varchar(255) COLLATE "pg_catalog"."default",
  "check_status" varchar(255) COLLATE "pg_catalog"."default",
  "estate_id" varchar(255) COLLATE "pg_catalog"."default",
  "sync_time" varchar(255) COLLATE "pg_catalog"."default",
  "bdp_audit" varchar COLLATE "pg_catalog"."default",
  "unionkey" varchar COLLATE "pg_catalog"."default",
  "user_design_id" int8
)
;
COMMENT ON TABLE "public"."t_dc_area_building_info" IS '智慧社区_楼房信息表';
