export default {
  gsglData: {
    // 高速公路左侧面板数据
    gsglsl: 1,
    zddw: 14,
    name: "高速公路档案",
    id: "6987FC234EC3456789AFC2984E7669E4",
    lcqc: 333,
    list: [
      {
        qidian: "石家庄",
        zddwgs: 14,
        id: "6987FC234EC3F28BD8AFC2984E7669E4",
        zhidian: "雄安",
        title: "京雄高速",
        changdu: 333,
        info: "北京—雄安新区高速公路是北京市、河北省境内高速公路，为雄安新区规划纲要确定的构建“四纵三横”区域高速公路网组成部分，是雄安新区对外骨干路网。",
      }
    ],
  },
  // 右侧面板详情数据根据id拿到对应的数据 目前模拟了两条数据
  '6987FC234EC3F28BD8AFC2984E7669E4': [
    {
      count: 2,
      id: "24ac52eff48143cb8b9baa7d4da7d5b6",
      name: "高速出入口",
      children: [
        {
          id: "gscrk1",
          group: "gsgl",
          name: "雄安郊野公园、白洋淀站出入口",
          imgName: "出入口",
          juli: "92.0",
          coordinates: [496222.96875, 4323700.5,0],
          info:{
              "ssxq":"所属辖区",
              "gsgxdd":'高速管辖大队',
              "fzr":"负责人",
              "dh":"电话",
              "jwd":"经纬度",
              "bz":"备注"
          },
          data: {
            jwd: "115.95637,39.0468",
            gsgxdd: "容城县公安局",
            dh: "xxx",
            fzr: "xxx",
            ssxq: "容城县公安局",
            bz: "未设收费站",
          },
        },
        {
          id: "gscrk2",
          group: "gsgl",
          name: "津雄高速出入口",
          imgName: "出入口",
          juli: "96.0",
          coordinates: [495679.875, 4327840.5, 0],
          info:{
              "ssxq":"所属辖区",
              "gsgxdd":'高速管辖大队',
              "fzr":"负责人",
              "dh":"电话",
              "jwd":"经纬度",
              "bz":"备注"
          },
          data: {
            jwd: "115.95007,39.08409",
            gsgxdd: "容城县公安局",
            dh: "xxx",
            fzr: "xxx",
            ssxq: "容城县公安局",
            bz: "高速互通",
          },
        },
      ],
    },
    {
      count: 11,
      id: "8e7a981fe55d47ba91a28a39760c5ee5",
      name: "高速桥梁",
      children: [
        {
          id: "gsql1",
          group: "gsgl",
          name: "跨津雄高速桥",
          imgName: "高速桥梁",
          juli: "96.4",
          coordinates: [496148.71875, 4324055.5, 0],
          info:{
              "cd":"长度(米)",
              "lb":"类别",
              "gxgajg":"管辖公安机关",
              "jwd":"经纬度",
              "bz":"备注",
          },
          data: {
              "cd":"35.0",
              "lb":"其它桥",
              "gxgajg":"容城县公安局",
              "jwd":"115.95551,39.05",
              "bz":"Invalid",
          },
        },
        {
          id: "gsql2",
          group: "gsgl",
          name: "南拒马右堤桥",
          imgName: "高速桥梁",
          juli: "90.2",
          coordinates: [495597.84375, 4329690, 0],
          info:{
              "cd":"长度(米)",
              "lb":"类别",
              "gxgajg":"管辖公安机关",
              "jwd":"经纬度",
              "bz":"备注",
          },
          data: {
              "cd":"80.0",
              "lb":"其它桥",
              "gxgajg":"容城县公安局",
              "jwd":"115.94911,39.10075",
              "bz":"",
          },
        },
        {
          id: "gsql3",
          group: "gsgl",
          name: "无名桥",
          imgName: "高速桥梁",
          juli: "90.3",
          coordinates: [495663.53125, 4329619, 0],
          info:{
              "cd":"长度(米)",
              "lb":"类别",
              "gxgajg":"管辖公安机关",
              "jwd":"经纬度",
              "bz":"备注",
          },
          data: {
              "cd":"35.0",
              "lb":"其它桥",
              "gxgajg":"容城县公安局",
              "jwd":"115.95551,39.05",
              "bz":"",
          },
        },
        {
          id: "gsql4",
          group: "gsgl",
          name: "朱庄村桥",
          imgName: "高速桥梁",
          juli: "91.0",
          coordinates: [495571.53125, 4328979.5, 0],
          info:{
              "cd":"长度(米)",
              "lb":"类别",
              "gxgajg":"管辖公安机关",
              "jwd":"经纬度",
              "bz":"备注",
          },
          data: {
              "cd":"30.0",
              "lb":"其它桥",
              "gxgajg":"容城县公安局",
              "jwd":"115.94881,39.09435",
              "bz":"",
          },
        },
        {
          id: "gsql5",
          group: "gsgl",
          name: "无名桥",
          imgName: "高速桥梁",
          juli: "91.7",
          coordinates: [495625.625, 4328345.5, 0],
          info:{
              "cd":"长度(米)",
              "lb":"类别",
              "gxgajg":"管辖公安机关",
              "jwd":"经纬度",
              "bz":"备注",
          },
          data: {
              "cd":"30.0",
              "lb":"其它桥",
              "gxgajg":"容城县公安局",
              "jwd":"115.94944,39.08864",
              "bz":"",
          },
        },
        {
          id: "gsql6",
          group: "gsgl",
          name: "容易线桥",
          imgName: "高速桥梁",
          juli: "92.4",
          coordinates: [495677.90625, 4327491, 0],
          info:{
              "cd":"长度(米)",
              "lb":"类别",
              "gxgajg":"管辖公安机关",
              "jwd":"经纬度",
              "bz":"备注",
          },
          data: {
              "cd":"70.0",
              "lb":"其它桥",
              "gxgajg":"容城县公安局",
              "jwd":"115.95005,39.08094",
              "bz":"",
          },
        },
        {
          id: "gsql7",
          group: "gsgl",
          name: "保津高铁跨线桥",
          imgName: "高速桥梁",
          juli: "93.2",
          coordinates: [495788.375, 4326803.5, 0],
          info:{
              "cd":"长度(米)",
              "lb":"类别",
              "gxgajg":"管辖公安机关",
              "jwd":"经纬度",
              "bz":"备注",
          },
          data: {
              "cd":"20.0",
              "lb":"上跨桥",
              "gxgajg":"容城县公安局",
              "jwd":"115.95133,39.07475",
              "bz":"",
          },
        },
        {
          id: "gsql8",
          group: "gsgl",
          name: "新S333跨线桥",
          imgName: "高速桥梁",
          juli: "93.3",
          coordinates: [495804.71875, 4326688, 0],
          info:{
              "cd":"长度(米)",
              "lb":"类别",
              "gxgajg":"管辖公安机关",
              "jwd":"经纬度",
              "bz":"备注",
          },
          data: {
              "cd":"40",
              "lb":"上跨桥",
              "gxgajg":"容城县公安局",
              "jwd":"115.95152,39.07371",
              "bz":"",
          },
        },
        {
          id: "gsql9",
          group: "gsgl",
          name: "乐安街桥",
          imgName: "高速桥梁",
          juli: "94.2",
          coordinates: [496000.71875, 4325834.5, 0],
          info:{
              "cd":"长度(米)",
              "lb":"类别",
              "gxgajg":"管辖公安机关",
              "jwd":"经纬度",
              "bz":"备注",
          },
          data: {
              "cd":"70.0",
              "lb":"其它桥",
              "gxgajg":"容城县公安局",
              "jwd":"115.95379,39.06602",
              "bz":"",
          },
        },
        {
          id: "gsql10",
          group: "gsgl",
          name: "金湖街桥",
          imgName: "高速桥梁",
          juli: "95.1",
          coordinates: [496130.96875, 4324981.5, 0],
          info:{
              "cd":"长度(米)",
              "lb":"类别",
              "gxgajg":"管辖公安机关",
              "jwd":"经纬度",
              "bz":"备注",
          },
          data: {
              "cd":"35.0",
              "lb":"其它桥",
              "gxgajg":"容城县公安局",
              "jwd":"115.9553,39.05834",
              "bz":"",
          },
        },
        {
          id: "gsql11",
          group: "gsgl",
          name: "无名桥",
          imgName: "高速桥梁",
          juli: "95.8",
          coordinates: [496176.5625, 4324356.5, 0],
          info:{
              "cd":"长度(米)",
              "lb":"类别",
              "gxgajg":"管辖公安机关",
              "jwd":"经纬度",
              "bz":"备注",
          },
          data: {
              "cd":"35.0",
              "lb":"其它桥",
              "gxgajg":"容城县公安局",
              "jwd":"115.95583,39.05271",
              "bz":"",
          },
        },
      ],
    },
    {
      count: 1,
      id: "8e7a981fe55d47ba345628a39760c5ee5",
      name: "高速结合部协议",
      children: [
        {
          id: "gsjhb1",
          group: "gsgl",
          name: "京雄高速",
          imgName: "高速结合部",
          juli: "89.2",
          coordinates: [495813.8125, 4330719,0],
          info:{
              "cd":"协议双方",
              "lb":"F4",
              "gxgajg":"结合部",
              "jjd":"交接地",
              "jwd":"经纬度",
              "bz":"签订时",
          },
          data: {
              "cd":"新区公安局特勤支队",
              "lb":"保定市公安局警卫支队",
              "gxgajg":"89.2",
              "jjd":"南拒马河中央",
              "jwd":"115.9516,39.11002",
              "bz":"2022.5.13",
          },
        },
      ],
    },
  ],
};
