export default {
  gstlData: {
    // 高速铁路左侧面板数据
    gstlsl: 1,
    zddw: 17,
    name: "高速铁路路档案",
    id: "0779A2DA4565A9E1E62816BE91234564",
    lcqc: 106.55,
    list: [
      {
        zddwgs: 17,
        id: "0779A2DA4565A9E1E62816BE9DE982C4",
        title: "京雄城际铁路",
        changdu: 106.55,
        info: "京雄城际铁路（Beijing-Xiong'an Intercity Railway），是中国境内一条连接北京市与河北省雄安新区的城际铁路，是完善京津冀区域高速铁路网结构的重要铁路线路。",
      },
    ],
  },
  // 右侧面板详情数据根据id拿到对应的数据 目前模拟了两条数据
  '0779A2DA4565A9E1E62816BE9DE982C4': [
    {
      count: 1,
      id: "24ac52eff48143cb8b9baa7d4da7d5b6",
      name: "高铁车站登记情况",
      children: [
        {
          id: "gstlcz1",
          group: "gstl",
          name: "雄安站",
          imgName: "高铁",
          juli: "106.05",
          coordinates: [513416.46875, 4325263, 0],
          info: {
            qzd: "属地公安机关",
            znjl: "站内距离",
            sdgajg: "负责人",
            lxfs: "联系方式",
            ssqx: "所属县区",
            jwd: "经纬度",
            bz: "备注",
          },
          data: {
            qzd: "廊坊市公安局警卫支队",
            znjl: "雄安新区公安局特勤支队",
            sdgajg: "xxxxxx",
            lxfs: "xxxxxx",
            ssqx: "雄安站枢纽片区",
            jwd: "116.15501,39.06078",
            bz: "",
          },
        },
      ],
    },
    {
      count: 1,
      id: "24ac52eff481aaab8b9baa7d4da7d5b6",
      name: "高铁结合部协议",
      children: [
        {
          id: "gstljhb1",
          group: "gstl",
          name: "京雄城际铁路",
          imgName: "高铁结合部协议",
          juli: "93.816",
          coordinates: [521392.625, 4334035.5, 0],
          info: {
            qzd: "F4",
            znjl: "协议双方",
            sdgajg: "签订时间",
            jwd: "经纬度",
            bz: "备注",
          },
          data: {
            qzd: "廊坊市公安局警卫支队",
            znjl: "雄安新区公安局特勤支队",
            sdgajg: "2020.11.23",
            jwd: "116.24744,39.13964",
            bz: "216号桥墩",
          },
        },
      ],
    },
    {
      count: 1,
      id: "8e7a981fe55d47ba91a28a39760c5ee5",
      name: "高铁桥梁",
      children: [
        {
          id: "gstlgjq1",
          group: "gstl",
          name: "雄安站",
          imgName: "桥梁",
          juli: "100.183",
          coordinates: [516412.625, 4329954.5, 0],
          info: {
            qzd: "长度(千米)",
            znjl: "类别",
            sdgajg: "属地公安机关",
            jwd: "经纬度",
            bz: "备注",
          },
          data: {
            qzd: "12.734",
            znjl: "其它桥",
            sdgajg: "雄县公安局",
            jwd: "116.18974,39.10299",
            bz: "",
          },
        },
      ],
    },
    {
      count: 2,
      id: "bc79621e3f4b4291b123de56818fccdc",
      name: "高铁沿线复杂村镇",
      children: [
        {
          id: "gstlfzcz1",
          group: "gstl",
          name: "八西村",
          imgName: "复杂村落",
          juli: "96.00",
          coordinates: [519643.375, 4332753, 0],
          info: {
            qzd: "负责人",
            znjl: "电话",
            sdgajg: "与铁路关系",
            sdjig: "属地公安机关",
            jwd: "经纬度",
            bz: "备注",
          },
          data: {
            qzd: "xxx",
            znjl: "xxx",
            sdgajg: "方向东，距离70米",
            sdjig: "米家务派出所",
            jwd: "116.22717,39.12813",
            bz: "",
          },
        },
        {
          id: "gstlfzcz2",
          group: "gstl",
          name: "板东村",
          imgName: "复杂村落",
          juli: "98.1",
          coordinates: [518064.46875, 4331593.5, 0],
          info: {
            qzd: "负责人",
            znjl: "电话",
            sdgajg: "与铁路关系",
            sdjig: "属地公安机关",
            jwd: "经纬度",
            bz: "备注",
          },
          data: {
            qzd: "xxx",
            znjl: "xxx",
            sdgajg: "方向西北，距离50米",
            sdjig: "米家务派出所",
            jwd: "116.20888,39.11772",
            bz: "",
          },
        },
      ],
    },
    {
      count: 2,
      id: "bc79621e3f4bddd42912354de56818fccdc",
      name: "高铁四电所",
      children: [
        {
          id: "gstlsds1",
          group: "gstl",
          name: "四电站",
          imgName: "高铁四电所",
          juli: "96.322",
          coordinates: [519399.09375, 4332601.5, 0],
          info: {
            ksqk: "看守情况",
            sdgajg: "属地公安机关",
            jwd: "经纬度",
            bz: "备注",
          },
          data: {
            ksqk: "有",
            sdgajg: "米家务派出所",
            jwd: "116.22434,39.12677",
            bz: "291-292 西侧",
          },
        },
        {
          id: "gstlsds2",
          group: "gstl",
          name: "四电站",
          imgName: "高铁四电所",
          juli: "99.766",
          coordinates: [516772.46875, 4330357.5, 0],
          info: {
            ksqk: "看守情况",
            sdgajg: "属地公安机关",
            jwd: "经纬度",
            bz: "备注",
          },
          data: {
            ksqk: "有",
            sdgajg: "米家务派出所",
            jwd: "116.19391,39.10661",
            bz: "Z395-Z397东侧",
          },
        },
      ],
    },
    {
      count: 2,
      id: "bc79621e3f4bddd4291b123de56818fccdc",
      name: "高铁基站",
      children: [
        {
          id: "gstljz1",
          group: "gstl",
          name: "基站",
          imgName: "高铁基站",
          juli: "96.073",
          coordinates: [519588.15625, 4332712, 0],
          info: {
            ksqk: "看守情况",
            sdgajg: "属地公安机关",
            jwd: "经纬度",
            bz: "备注",
          },
          data: {
            ksqk: "有",
            sdgajg: "米家务派出所",
            jwd: "116.22653,39.12776",
            bz: "284-285西侧",
          },
        },
        {
          id: "gstljz2",
          group: "gstl",
          name: "基站",
          imgName: "高铁基站",
          juli: "99.460",
          coordinates: [516842.40625, 4330435, 0],
          info: {
            ksqk: "看守情况",
            sdgajg: "属地公安机关",
            jwd: "经纬度",
            bz: "备注",
          },
          data: {
            ksqk: "有",
            sdgajg: "米家务派出所",
            jwd: "116.19472,39.10731",
            bz: "Z391-Z392西侧",
          },
        },
      ],
    },
    {
      count: 8,
      id: "bc79621e3f4bd777978b123de56818fccdc",
      name: "高铁疏散梯",
      children: [
        {
          id: "gstlsst1",
          group: "gstl",
          name: "疏散梯",
          imgName: "疏散梯",
          juli: "96.206",
          coordinates: [519463.8125, 4332653, 0],
          info: {
            ksqk: "看守情况",
            sdgajg: "属地公安机关",
            jwd: "经纬度",
            bz: "备注",
          },
          data: {
            ksqk: "有",
            sdgajg: "米家务派出所",
            jwd: "116.22509,39.12723",
            bz: "288-289  西侧",
          },
        },
        {
          id: "gstlsst2",
          group: "gstl",
          name: "疏散梯",
          imgName: "疏散梯",
          juli: "99.308",
          coordinates: [517058.125, 4330662, 0],
          info: {
            ksqk: "看守情况",
            sdgajg: "属地公安机关",
            jwd: "经纬度",
            bz: "备注",
          },
          data: {
            ksqk: "有",
            sdgajg: "米家务派出所",
            jwd: "116.19722,39.10935",
            bz: "Z381-Z382 东侧",
          },
        },
        {
          id: "gstlsst3",
          group: "gstl",
          name: "疏散梯",
          imgName: "疏散梯",
          juli: "101.986",
          coordinates: [515789.125, 4329012, 0],
          info: {
            ksqk: "看守情况",
            sdgajg: "属地公安机关",
            jwd: "经纬度",
            bz: "备注",
          },
          data: {
            ksqk: "有",
            sdgajg: "米家务派出所",
            jwd: "116.18251,39.09451",
            bz: "Y463-Y462 西侧",
          },
        },
        {
          id: "gstlsst4",
          group: "gstl",
          name: "疏散梯",
          imgName: "疏散梯",
          juli: "102.613",
          coordinates: [515082.90625, 4327799.5, 0],
          info: {
            ksqk: "看守情况",
            sdgajg: "属地公安机关",
            jwd: "经纬度",
            bz: "备注",
          },
          data: {
            ksqk: "有",
            sdgajg: "米家务派出所",
            jwd: "116.17432,39.0836",
            bz: "Z483-Z484 中间",
          },
        },
        {
          id: "gstlsst5",
          group: "gstl",
          name: "疏散梯",
          imgName: "疏散梯",
          juli: "104.5",
          coordinates: [514243.5625, 4326415.5, 0],
          info: {
            ksqk: "看守情况",
            sdgajg: "属地公安机关",
            jwd: "经纬度",
            bz: "备注",
          },
          data: {
            ksqk: "有",
            sdgajg: "大营镇派出所",
            jwd: "116.16459,39.07115",
            bz: "Y535-Y536 西侧",
          },
        },
        {
          id: "gstlsst6",
          group: "gstl",
          name: "疏散梯",
          imgName: "疏散梯",
          juli: "104.68",
          coordinates: [514184.15625, 4326234.5, 0],
          info: {
            ksqk: "看守情况",
            sdgajg: "属地公安机关",
            jwd: "经纬度",
            bz: "备注",
          },
          data: {
            ksqk: "有",
            sdgajg: "雄安站分局",
            jwd: "116.1639,39.06952",
            bz: "Z538-Z539 东侧",
          },
        },
        {
          id: "gstlsst7",
          group: "gstl",
          name: "疏散梯",
          imgName: "疏散梯",
          juli: "105.48",
          coordinates: [513563.40625, 4325374, 0],
          info: {
            ksqk: "看守情况",
            sdgajg: "属地公安机关",
            jwd: "经纬度",
            bz: "备注",
          },
          data: {
            ksqk: "有",
            sdgajg: "雄安站分局",
            jwd: "116.15671,39.06178",
            bz: "西侧",
          },
        },
        {
          id: "gstlsst8",
          group: "gstl",
          name: "疏散梯",
          imgName: "疏散梯",
          juli: "106.860",
          coordinates: [513349.3125, 4324533.5, 0],
          info: {
            ksqk: "看守情况",
            sdgajg: "属地公安机关",
            jwd: "经纬度",
            bz: "备注",
          },
          data: {
            ksqk: "有",
            sdgajg: "雄安站分局",
            jwd: "116.15422,39.05421",
            bz: "西侧",
          },
        },
      ],
    },
  ],
};
